### ISSUE TITLE
editation of tags in platform donot triger regeneration

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#161] opened 2020-02-28 17:58 UTC
Hitted like:
tag1tag2
edited to
tag1 tag2  - no job rewritten, regenerate all had to e used

**Comment by oklinov** [comment] 2020-09-22 13:48
Couldn't reproduce it on the latest version -> closing

**Closed by oklinov** 2020-09-22 13:48 UTC
